### PR TITLE
LPS-56306 Improve UI of push portlet with consistent message-

### PR DESCRIPTION
**Pull request by javiergamarra**
Some Juan's suggestions in UI and messages. 

This is the last pull (apart from the model device, model OS that is pending of an implementation decision) of changes in the portlet.

### CODE REVIEW

**Comment by brunofarache** [comment]
Just started reviewing <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brunofarache** [comment]
@nhpatt: I think it would a good idea to separate tabs like that:

Move "Devices" to the first position:
Devices | Configuration

Move "Test" to inside Configuration, and turn "Android" and "iOS" into internal tabs as well:

Configuration
Android | iOS | Test

What do you think? I think it will be better organized! It also gives priority to the "Devices" tab, which is more important and will be more used than Configuration (which is typically used only once).

**Comment by nhpatt** [comment]
I agree with you that devices is going to be used more often than configuration, I presented the tabs to @juanferrub in that order but we changed them back because it could confuse the user the first time that enters the menu (because devices will be empty).

I like the idea of merging configuration and testing and add two internal tabs.

**Comment by brunofarache** [comment]
No, I can do it, it's easy.

**Comment by brunofarache** [comment]
Forwarded to Brian.

@nhpatt you can check detailed commits in this branch:

https://github.com/brunofarache/liferay-plugins-ee/commits/tabs

It was hard to patch ee-6.2.x and master and keep separate commits, I had to squash all them in one, I hope Brian doesn't mind.

**Comment by nhpatt** [comment]
Thanks, I'll check the changes! :D

I'll also send you an email with some doubts/several things :P

**Comment by brunofarache** [comment]
Here is it looks like now: screenshot

**Comment by brunofarache** [comment]
oh, wow, Brian merged with no fear!

**Pull request closed without merging**
